import unittest,sys,json,threading,urllib.request,urllib.error,os
from pathlib import Path
from datetime import datetime,timezone
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from unittest.mock import patch
import astro,places,timing
import server as app_server
from server import Handler,ThreadingHTTPServer
class ChartTests(unittest.TestCase):
 def profile(self):return {'name':'Test','date':'1989-10-15','time':'20:30','place':places.LOCAL.copy()}
 def test_reference_positions_and_time_boundary(self):
  c=astro.calculate(self.profile(),datetime(2026,9,30,tzinfo=timezone.utc))
  self.assertEqual(c['birth_utc'],'1989-10-15T15:00:00+00:00');self.assertEqual(c['ascendant']['sign'],'Taurus');self.assertAlmostEqual(c['ascendant']['degree'],19.98441,places=3)
  self.assertEqual(c['charts']['9']['ascendant'],'Gemini');self.assertTrue(c['charts']['9']['sensitive']);self.assertEqual(c['charts']['10']['ascendant'],'Cancer');self.assertEqual(len(c['charts']),17);self.assertIn('81',c['charts'])
  moon=next(p for p in c['planets'] if p['name']=='Moon');self.assertEqual(moon['nakshatra'],'Ashwini');self.assertEqual(moon['pada'],3)
  self.assertEqual(c['dashas']['current']['lord'],'Moon');self.assertEqual(next(s for s in c['dashas']['current']['subperiods'] if s['current'])['lord'],'Venus')
 def test_relationship_questions_answer_the_requested_topic(self):
  c=astro.calculate(self.profile(),datetime(2026,9,30,tzinfo=timezone.utc))
  for n in [1,9,10]:
   for question in ['when i get married','When will I marry?','What year is my wedding?','मेरी शादी कब होगी','shaadi kab hogi']:
    text=astro.reading(c,question,n)
    self.assertTrue(text.startswith('Marriage timing:'))
    self.assertIn('not a predicted wedding date',text)
    self.assertIn(f'Relationships in D{n}',text)
    self.assertNotIn('Learning:',text)
    self.assertNotIn('Career:',text)
    ruler=astro.RULERS[(c['charts'][str(n)]['ascendant_index']+6)%12]
    placement=next(p for p in c['charts'][str(n)]['planets'] if p['name']==ruler)
    self.assertIn(f"{ruler} is in {placement['sign']}, house {placement['house']}",text)
  self.assertTrue(astro.reading(c,'Tell me about my spouse').startswith('Relationships in D1'))
 def test_timing_candidates_and_topic_routing(self):
  c=astro.calculate(self.profile(),datetime(2026,9,30,tzinfo=timezone.utc))
  c['timing_analysis']=timing.build(c)
  for topic in timing.TOPICS:
   data=c['timing_analysis'][topic]
   self.assertEqual(data['rule_version'],'editorial-screen-v1')
   start=datetime.fromisoformat(data['horizon_start']);end=datetime.fromisoformat(data['horizon_end'])
   for w in data['windows']:
    self.assertLess(datetime.fromisoformat(w['start']),datetime.fromisoformat(w['end']))
    self.assertGreaterEqual(datetime.fromisoformat(w['start']),start)
    self.assertLessEqual(datetime.fromisoformat(w['end']),end)
    self.assertTrue(w['reasons'])
    for sample in w['transit_samples']:
     self.assertGreaterEqual(sample['date'],w['start']);self.assertLess(sample['date'],w['end'])
     for match in sample['matches']:
      index=astro.SIGNS.index(match['sign'])
      offsets=[0,4,6,8] if match['planet']=='Jupiter' else [0,2,6,9]
      self.assertTrue(all(astro.SIGNS.index(target) in [(index+offset)%12 for offset in offsets] for target in match['target_signs']))
  with patch.object(timing,'transit_samples',side_effect=AssertionError('Reuse cached timing analysis')):
   self.assertIn('Traditional candidate periods',astro.reading(c,'when i get married'))
   wealth=astro.reading(c,'When will I be rich?',2)
   self.assertIn('Money and wealth timing',wealth);self.assertIn('D2 Hora',wealth)
   self.assertNotIn('Career:',wealth)
  combined=astro.reading(c,'marriage and wealth timing')
  self.assertIn('Marriage timing',combined);self.assertIn('Money and wealth timing',combined)
  self.assertIn('Basic mode did not recognize',astro.reading(c,'Will I win a lottery?'))
  self.assertIn('D1 Moon:',astro.reading(c,'Where is my Moon?'))
  self.assertIn('cannot diagnose',astro.reading(c,'health and money'))
  self.assertNotIn('Career:',astro.reading(c,'money',9))
  empty=dict(c,dashas={'timeline':[]})
  self.assertEqual(timing.analyze(empty,'marriage',[])['windows'],[])
  dates=list(timing.monthly_dates(datetime(2026,12,20,tzinfo=timezone.utc),datetime(2027,2,1,tzinfo=timezone.utc)))
  self.assertEqual([d.strftime('%Y-%m-%d') for d in dates],['2026-12-20','2027-01-01'])
 def test_bilingual_translation_preserves_chart_facts(self):
  import hindi
  c=astro.calculate(self.profile(),datetime(2026,9,30,tzinfo=timezone.utc));c['timing_analysis']=timing.build(c)
  with patch.object(app_server.pipeline,'ollama',side_effect=AssertionError('Hindi facts must not be generated by a model')):
   summary=hindi.summary(c,'Explain Moon',1)
   moon=next(p for p in c['planets'] if p['name']=='Moon')
   self.assertIn(hindi.SIGNS[moon['sign']],summary)
   self.assertIn(f"भाव {moon['house']}",summary)
   result=app_server.localized_result({'text':'English interpretation','grounded_hi':summary},'both')
   self.assertEqual(result['translations']['hi'],summary)
   self.assertEqual(result['mode'],'grounded_hindi')
   unrelated=app_server.localized_result({'text':'Invent a wedding date'},'hi')
   self.assertNotIn('hi',unrelated['translations'])
   self.assertEqual(unrelated['text'],'Invent a wedding date')
  marriage=hindi.summary(c,'when i get married')
  for w in c['timing_analysis']['marriage']['windows'][:3]:
   self.assertIn(w['start'][:10],marriage);self.assertIn(w['end'][:10],marriage)
  self.assertIn('पक्की तारीख नहीं',marriage)
  self.assertIsNone(hindi.summary(c,'Will I win a lottery?'))
  self.assertEqual(app_server.translate_text('Explain my Moon placement briefly'),hindi.QUESTIONS['Explain my Moon placement briefly'])
 def test_llm_summary_uses_selected_facts_and_conversation(self):
  c=astro.calculate(self.profile(),datetime(2026,9,30,tzinfo=timezone.utc));c['timing_analysis']=timing.build(c)
  with patch.dict(os.environ,{'OLLAMA_MODEL':'test-local-model'}),patch.object(app_server.pipeline,'ollama',return_value={'message':{'content':'A concise relationship answer.'}}) as model:
   result=app_server.english_answer(c,'when i get married',[{'role':'user','content':'Earlier question'}],division=9)
   self.assertEqual(result['mode'],'llm')
   payload=model.call_args.args[1];context=json.loads(payload['messages'][-1]['content'])
   self.assertEqual(context['chart_facts']['selected_division'],9)
   self.assertEqual(context['question'],'when i get married')
   self.assertEqual(context['recent_conversation'][0]['content'],'Earlier question')
   self.assertNotIn('charts',context['chart_facts'])
   self.assertEqual(payload['options']['num_predict'],450)
   self.assertEqual(set(context['chart_facts']['marriage_charts']),{'1','9'})
   self.assertEqual(len(context['chart_facts']['timing_analysis']['marriage']['placements']),2)
   app_server.english_answer(c,'Then tell the reason and give time',[{'role':'user','content':'When could I get married?'}],division=10)
   follow=json.loads(model.call_args.args[1]['messages'][-1]['content'])
   self.assertIn('marriage',follow['chart_facts']['timing_analysis'])
   self.assertIn('Marriage timing',follow['basic_reading'])
 def test_division_explanations(self):
  d=astro.division_details(47.5,9)
  self.assertEqual(d['natal_position'], 'Taurus 17°30′00″')
  self.assertEqual(d['segment'],6)
  self.assertEqual(d['mapped_sign'],'Gemini')
  self.assertAlmostEqual(d['mapped_degree'],7.5)
  self.assertAlmostEqual(astro.division_details(47.5,10)['mapped_degree'],25)
  self.assertEqual(astro.division_details(35,30)['mapped_degree'],0)
  self.assertEqual(astro.division_details(47.5,10)['mapped_sign'],'Gemini')
  self.assertEqual(astro.division_details(35,30)['segment'],2)
  self.assertEqual(astro.division_details(35,30)['segment_width_degree'],7)
  self.assertEqual(astro.division_details(360,1)['natal_sign'],'Aries')
  for n in astro.VARGAS:
   for x in [0,29.99999,30,47.5,359.99999]:
    m=astro.division_details(x,n)
    self.assertEqual(m['mapped_sign'],astro.SIGNS[astro.division(x,n)])
    self.assertLessEqual(m['segment_start_degree'],m['natal_degree'])
    self.assertLess(m['natal_degree'],m['segment_end_degree'])
  with self.assertRaises(ValueError):astro.division_details(float('nan'),9)
 def test_timezone_invalid_and_ambiguous(self):
  for date,time in [('2020-03-08','02:30'),('2020-11-01','01:30')]:
   with self.assertRaises(ValueError):astro.utc_birth(date,time,'America/New_York')
  with self.assertRaises(ValueError):astro.utc_birth('2020-02-31','12:00','Asia/Kolkata')
 def test_varga_boundaries(self):
  self.assertEqual(astro.division(49.9999,9),2);self.assertEqual(astro.division(50,9),3)
  self.assertEqual(astro.division(4.99,30),0);self.assertEqual(astro.division(5,30),10)
  self.assertEqual(astro.division(34.99,30),1);self.assertEqual(astro.division(35,30),5)
 def test_api_flow_isolation_and_delete(self):
  server=ThreadingHTTPServer(('127.0.0.1',0),Handler);threading.Thread(target=server.serve_forever,daemon=True).start();base='http://127.0.0.1:'+str(server.server_port)
  def post(path,data,token=''):
   req=urllib.request.Request(base+path,data=json.dumps(data).encode(),headers={'Content-Type':'application/json','Authorization':'Bearer '+token});return json.load(urllib.request.urlopen(req))
  try:
   html=urllib.request.urlopen(base).read();self.assertIn(b'Generate my reading',html);self.assertNotIn(b'Research mode',html)
   r=post('/api/reading',{'name':'Test','date':'1989-10-15','time':'20:30','place_id':places.LOCAL['id']});self.assertEqual(r['answer']['mode'],'basic')
   with self.assertRaises(urllib.error.HTTPError):post('/api/chat',{'question':'money'},'wrong-token')
   follow=post('/api/chat',{'question':'money'},r['token']);self.assertIn('Mercury',follow['text'])
   for n in astro.VARGAS:
    chosen=post('/api/chart-reading',{'division':n},r['token'])
    self.assertIn(f'D{n}',chosen['text'])
    if n!=1:
     for planet in r['chart']['charts'][str(n)]['planets']:
      self.assertIn(f"{planet['name']}: {planet['sign']}, house {planet['house']}",chosen['text'])
   with self.assertRaises(urllib.error.HTTPError):post('/api/chart-reading',{'division':5},r['token'])
   with self.assertRaises(urllib.error.HTTPError):post('/api/chart-reading',{'division':9},'wrong-token')
   follow=post('/api/chat',{'question':'overview','division':9},r['token']);self.assertIn('D9',follow['text'])
   with patch.object(app_server,'translate_text',return_value='हिंदी उत्तर'), patch.object(astro,'calculate',side_effect=AssertionError('Translation must reuse chart')), patch.object(app_server,'english_answer',side_effect=AssertionError('Translate original answer only')):
    translated=post('/api/translate',{'text':'Original answer','language':'both'},r['token'])
    self.assertEqual(translated['translations'],{'en':'Original answer','hi':'हिंदी उत्तर'})
   with self.assertRaises(urllib.error.HTTPError):post('/api/translate',{'text':'test','language':'fr'},r['token'])
   with self.assertRaises(urllib.error.HTTPError):post('/api/translate',{'text':'test','language':'hi'},'wrong-token')
   def stream(path,data):
    req=urllib.request.Request(base+path,data=json.dumps(data).encode(),headers={'Content-Type':'application/json','Authorization':'Bearer '+r['token']})
    with urllib.request.urlopen(req) as res:
     self.assertIn('application/x-ndjson',res.headers['Content-Type'])
     return [json.loads(line) for line in res if line.strip()]
   with patch.dict(os.environ,{'OLLAMA_MODEL':'test-local-model'}),patch.object(app_server.pipeline,'ollama_stream',return_value=iter(['Mars is ', 'in Gemini, house 2.'])):
    events=stream('/api/chat-stream',{'question':'Explain Mars','division':1,'language':'both'})
    self.assertEqual(events[-1]['type'],'done')
    self.assertEqual(events[-1]['answer']['translations']['en'],'Mars is in Gemini, house 2.')
    self.assertIn('hi',events[-1]['answer']['translations'])
    self.assertGreater(len([e for e in events if e['type']=='delta']),2)
    self.assertEqual(app_server.SESSIONS[r['token']]['history'][-1]['content'],'Mars is in Gemini, house 2.')
   with patch.dict(os.environ,{'OLLAMA_MODEL':'test-local-model'}),patch.object(app_server.pipeline,'ollama_stream',return_value=iter(['प्रश्न 3'])):
    events=stream('/api/translate-stream',{'text':'Question 2','language':'hi'})
    self.assertNotIn('hi',events[-1]['answer']['translations'])
    self.assertEqual(events[-1]['answer']['text'],'Question 2')
   app_server.SESSIONS[r['token']]['expires']=__import__('time').time()+5
   with patch.object(astro,'calculate',side_effect=AssertionError('Chat must reuse the chart')):
    for i in range(15):
     response=post('/api/chat',{'question':f'Explain career {i}','division':10},r['token'])
     self.assertIn('D10',response['text'])
   self.assertGreater(app_server.SESSIONS[r['token']]['expires'],__import__('time').time()+3500)
   self.assertLessEqual(len(app_server.SESSIONS[r['token']]['history']),12)
   self.assertTrue(post('/api/forget',{},r['token'])['deleted'])
   with self.assertRaises(urllib.error.HTTPError):post('/api/chat',{'question':'money'},r['token'])
  finally:server.shutdown();server.server_close()
if __name__=='__main__':unittest.main()
